# Generated by Django 4.2.4 on 2023-11-11 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('blog_body', models.TextField(verbose_name='записи блога')),
                ('author', models.CharField(max_length=100, verbose_name='имя автора')),
                ('date_publication', models.DateTimeField(verbose_name='дата и время публикации')),
                ('images', models.ImageField(blank=True, null=True, upload_to='blogImj/', verbose_name='изображения')),
            ],
            options={
                'verbose_name': 'запись',
                'verbose_name_plural': 'записи',
            },
        ),
    ]
